# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "s905x3-custom"
BBFILE_PATTERN_s905x3-custom = "^${LAYERDIR}/"
BBFILE_PRIORITY_s905x3-custom = "6"

LAYERDEPENDS_s905x3-custom = "core"
LAYERSERIES_COMPAT_s905x3-custom = "kirkstone"
