# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/yocto/layers/poky/meta \
  /home/yocto/layers/poky/meta-poky \
  /home/yocto/layers/poky/meta-yocto-bsp \
  /home/yocto/layers/meta-rockchip \
  /home/yocto/layers/meta-arm/meta-arm \
  /home/yocto/layers/meta-arm/meta-arm-toolchain \
  /home/yocto/layers/meta-openembedded/meta-oe \
  /home/yocto/layers/meta-openembedded/meta-python \
  /home/yocto/layers/meta-openembedded/meta-multimedia \
"

