# navonz_v1 — pinned snapshot layers (layers-pin/), no custom products layer
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/yocto/layers-pin/poky/meta \
  /home/yocto/layers-pin/poky/meta-poky \
  /home/yocto/layers-pin/poky/meta-yocto-bsp \
  /home/yocto/layers-pin/meta-arm/meta-arm \
  /home/yocto/layers-pin/meta-arm/meta-arm-toolchain \
  /home/yocto/layers-pin/meta-rockchip \
"
